INSERT INTO ifhprdmst VALUES ('1', 'asasasasassa');
INSERT INTO ifhprdmst VALUES ('2', 'asasasasassa');
INSERT INTO ifhprdmst VALUES ('3', 'asasasasassa');
INSERT INTO ifhprdmst VALUES ('4', 'asasasasassa');
INSERT INTO ifhprdmst VALUES ('5', 'asasasasassa');
INSERT INTO ifhprdmst VALUES ('6', 'asasasasassa');
INSERT INTO ifhprdmst VALUES ('7', 'asasasasassa');
INSERT INTO ifhprdmst VALUES ('8', 'asasasasassa');
INSERT INTO ifhprdmst VALUES ('9', 'Product 9');
INSERT INTO ifhprdmst VALUES ('10', 'asasasasassa');
INSERT INTO ifhprdmst VALUES ('11', 'asasasasassa');
INSERT INTO ifhprdmst VALUES ('12', 'asasasasassa');
