INSERT INTO ifhprdmst VALUES ('1', 'Product 0001');
INSERT INTO ifhprdmst VALUES ('2', 'Product 0002');
INSERT INTO ifhprdmst VALUES ('3', 'Product 0003');
INSERT INTO ifhprdmst VALUES ('4', 'Product 0004');
INSERT INTO ifhprdmst VALUES ('5', 'Product 0005');
INSERT INTO ifhprdmst VALUES ('6', 'Product 0006');
INSERT INTO ifhprdmst VALUES ('7', 'Product 0007');
INSERT INTO ifhprdmst VALUES ('8', 'Product 0008');
INSERT INTO ifhprdmst VALUES ('9', 'Product 0009');